dev: true

server:
  port: "3306"
  allow_origins:
    - "http://localhost:3000"

db:
  user_name: "resume_create_admin"
  password: "123456"
  address: "localhost:3306"
  db_name: "resume_create"

jwt:
  secret: "secretKey"
  issuer: "issuer"
  expires: 48
